[project]
name = "RAG"
version = "0.1.0"
description = "Building a RAG system using Python and LangChain"
authors = [
    { name = "Udbhav", github = "https://github.com/Udbhav-regadamilli" }
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "faiss-cpu>=1.13.2",
    "nltk>=3.9.4",
    "pymupdf>=1.27.2.2",
    "requests>=2.33.1",
    "sentence-transformers>=5.3.0",
]
